import Head from 'next/head'
import Demo from '../components/Demo'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Workout App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<div className='bg-gray-500 w-full h-full pb-4'>

<Demo />

</div>

    </div>
  )
}
